apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-pv
spec:
  capacity:
    storage: 1.5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /one2n/metrics